server:
  port: 1234
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_oauth2?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: hieuboy
    password: vip.hieuboy
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: vnp.qttt@gmail.com
    password: vip.hieuboy
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.connectiontimeout: 50000
    properties.mail.smtp.timeout: 50000
    properties.mail.smtp.writetimeout: 50000

app:
  auth:
    tokenSecret: JWTSuperSecretKey
    tokenExpirationMsec: 604800000 #-- Hết hạn token 7 ngày
  account:
    email-invalid-regex: '^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$' #-- Định dạng email đúng
    username-symbol-regex: '[$&+,:;=?@#|]' #-- Username không được chứa ký tự đặc biệt
    password-expiration-in-day: 90 #-- Hết hạn mật khẩu 70 ngày
    reset-totp-expiration-in-ms: 86400000 #-- Hết hạn mã TOTP 1 ngày
    active-totp-expiration-in-ms: 604800000 #-- Hết hạn mã TOTP 7 ngày
    code-digits: 8 #-- 8 Mã số
    expiration-in-ms: 600000 #-- Hết hạn 600000ms = 10p
  email-config:
    folder-email-default: /email_templates/
    file-email-active-account: email_active_account.ftl
    file-email-change-password: email_change_password.ftl
    file-email-expiration-password: email_expiration_password.ftl
    file-email-reset-password: email_reset_password.ftl
    file-email-signin: email_signin.ftl
    file-email-signup-active-account: email_signup_active_account.ftl
    active-link-in-email: http://localhost:1234/api/auth/active-account
    reset-link-in-email: http://localhost:1234/api/auth/reset-account
    send-email-notify-when-login: true
    send-email-notify-when-sign-up: true